"""empty message

Revision ID: 7eb12d582dae
Revises: 639ad7cf6c1d
Create Date: 2022-08-18 11:34:39.882962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb12d582dae'
down_revision = '639ad7cf6c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
