"""empty message

Revision ID: f6a3af867da9
Revises: 12378a7e0bcc
Create Date: 2022-07-17 21:56:50.418374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a3af867da9'
down_revision = '12378a7e0bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'latitude')
    # ### end Alembic commands ###
