"""empty message

Revision ID: f90140e3e316
Revises: 3529b483770c
Create Date: 2022-07-22 14:09:50.624974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90140e3e316'
down_revision = '3529b483770c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'latitude')
    # ### end Alembic commands ###
