"""empty message

Revision ID: 3529b483770c
Revises: f6a3af867da9
Create Date: 2022-07-21 14:24:22.588319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3529b483770c'
down_revision = 'f6a3af867da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'zipcode')
    op.drop_column('listings', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('zipcode', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
