"""empty message

Revision ID: 1f85ada09576
Revises: 777ae883040b
Create Date: 2022-07-26 11:50:55.340110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f85ada09576'
down_revision = '777ae883040b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image', sa.String(length=255), nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('images', 'image')
    # ### end Alembic commands ###
